spring:
  application:
    name: sleepinghero

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
# 커스텀 설정
help:
  inquiry-url: "https://www.google.com"